# Generated by scripts/generate_contract_types.py; do not edit.
from typing import Any, Dict, List, Literal, Optional, TypedDict

EvaluationStatus = Literal['checked_clean', 'checked_with_advisories', 'findings', 'incomplete', 'unsupported', 'invalid', 'internal_error']
AuthorityStatus = Literal['self_attested', 'host_attested']
EventType = Literal['session.opened', 'session.closed', 'message.observed', 'delivery.received', 'transport.gap', 'turn.started', 'action.declared', 'roll.observed', 'narration.obligation', 'narration.observed', 'evaluation.completed']
Provenance = Literal['observed', 'derived', 'inferred', 'reported', 'decided']


class Diagnostic(TypedDict, total=False):
    code: str
    message: str
    pointer: str
    evidence_refs: List[str]


class EvaluatorCoverage(TypedDict):
    id: str
    required: bool
    status: str
    eligible: int
    evaluated: int
    skipped: int
    skip_reasons: List[Diagnostic]


class EvaluationResultV1(TypedDict):
    schema_version: Literal["table.evaluation/1.0"]
    evaluation_id: str
    tool: Dict[str, str]
    subject: Dict[str, Any]
    status: EvaluationStatus
    exit_code: int
    authority_status: AuthorityStatus
    coverage: Dict[str, Any]
    cursor: Dict[str, Any]
    context: Dict[str, Optional[str]]
    findings: List[Dict[str, Any]]
    advisories: List[Dict[str, Any]]
    warnings: List[Diagnostic]
    errors: List[Diagnostic]


class TableEventV1(TypedDict):
    schema_version: Literal["table.event/1.0"]
    event_id: str
    campaign_id: str
    session_id: str
    session_sequence: int
    source: Dict[str, Any]
    occurred_at: str
    recorded_at: str
    principal: Dict[str, Any]
    event_type: EventType
    payload: Dict[str, Any]
    correlation_ids: List[str]
    causation_id: Optional[str]
    audience: List[str]
    visibility: str
    sensitivity: str
    provenance: Provenance
    integrity: Dict[str, Any]
