// Generated by scripts/generate_contract_types.py; do not edit.
export type EvaluationStatus = "checked_clean" | "checked_with_advisories" | "findings" | "incomplete" | "unsupported" | "invalid" | "internal_error";
export type AuthorityStatus = "self_attested" | "host_attested";
export type TableEventType = "session.opened" | "session.closed" | "message.observed" | "delivery.received" | "transport.gap" | "turn.started" | "action.declared" | "roll.observed" | "narration.obligation" | "narration.observed" | "evaluation.completed";
export type Provenance = "observed" | "derived" | "inferred" | "reported" | "decided";

export interface Diagnostic {
  code: string;
  message: string;
  pointer?: string;
  evidence_refs?: string[];
}

export interface EvaluatorCoverage {
  id: string;
  required: boolean;
  status: "evaluated" | "not_applicable" | "skipped" | "disabled" | "error";
  eligible: number;
  evaluated: number;
  skipped: number;
  skip_reasons: Diagnostic[];
}

export interface EvaluationResultV1 {
  schema_version: "table.evaluation/1.0";
  evaluation_id: string;
  tool: { name: string; version: string };
  subject: Record<string, unknown>;
  status: EvaluationStatus;
  exit_code: 0 | 1 | 2;
  authority_status: AuthorityStatus;
  coverage: Record<string, unknown>;
  cursor: Record<string, unknown>;
  context: Record<string, string | null>;
  findings: Array<Record<string, unknown>>;
  advisories: Array<Record<string, unknown>>;
  warnings: Diagnostic[];
  errors: Diagnostic[];
}

export interface TableEventV1 {
  schema_version: "table.event/1.0";
  event_id: string;
  campaign_id: string;
  session_id: string;
  session_sequence: number;
  source: Record<string, unknown>;
  occurred_at: string;
  recorded_at: string;
  principal: Record<string, unknown>;
  event_type: TableEventType;
  payload: Record<string, unknown>;
  correlation_ids: string[];
  causation_id: string | null;
  audience: string[];
  visibility: "private" | "table" | "public" | "system";
  sensitivity: "normal" | "personal" | "secret";
  provenance: Provenance;
  integrity: Record<string, unknown>;
}
