#!/usr/bin/env python3
"""Generate dependency-free Python and TypeScript contract declarations."""

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONTRACTS = ROOT / "tablekit" / "contracts"


def quoted(values):
    return ", ".join(repr(value) for value in values)


def load_enums():
    evaluation = json.loads((CONTRACTS / "table-evaluation-1.0.schema.json").read_text())
    event = json.loads((CONTRACTS / "table-event-1.0.schema.json").read_text())
    return {
        "status": evaluation["properties"]["status"]["enum"],
        "authority": evaluation["properties"]["authority_status"]["enum"],
        "event_type": event["properties"]["event_type"]["enum"],
        "provenance": event["properties"]["provenance"]["enum"],
    }


def python_text(enums):
    return f'''# Generated by scripts/generate_contract_types.py; do not edit.
from typing import Any, Dict, List, Literal, Optional, TypedDict

EvaluationStatus = Literal[{quoted(enums["status"])}]
AuthorityStatus = Literal[{quoted(enums["authority"])}]
EventType = Literal[{quoted(enums["event_type"])}]
Provenance = Literal[{quoted(enums["provenance"])}]


class Diagnostic(TypedDict, total=False):
    code: str
    message: str
    pointer: str
    evidence_refs: List[str]


class EvaluatorCoverage(TypedDict):
    id: str
    required: bool
    status: str
    eligible: int
    evaluated: int
    skipped: int
    skip_reasons: List[Diagnostic]


class EvaluationResultV1(TypedDict):
    schema_version: Literal["table.evaluation/1.0"]
    evaluation_id: str
    tool: Dict[str, str]
    subject: Dict[str, Any]
    status: EvaluationStatus
    exit_code: int
    authority_status: AuthorityStatus
    coverage: Dict[str, Any]
    cursor: Dict[str, Any]
    context: Dict[str, Optional[str]]
    findings: List[Dict[str, Any]]
    advisories: List[Dict[str, Any]]
    warnings: List[Diagnostic]
    errors: List[Diagnostic]


class TableEventV1(TypedDict):
    schema_version: Literal["table.event/1.0"]
    event_id: str
    campaign_id: str
    session_id: str
    session_sequence: int
    source: Dict[str, Any]
    occurred_at: str
    recorded_at: str
    principal: Dict[str, Any]
    event_type: EventType
    payload: Dict[str, Any]
    correlation_ids: List[str]
    causation_id: Optional[str]
    audience: List[str]
    visibility: str
    sensitivity: str
    provenance: Provenance
    integrity: Dict[str, Any]
'''


def ts_union(values):
    return " | ".join(json.dumps(value) for value in values)


def typescript_text(enums):
    return f'''// Generated by scripts/generate_contract_types.py; do not edit.
export type EvaluationStatus = {ts_union(enums["status"])};
export type AuthorityStatus = {ts_union(enums["authority"])};
export type TableEventType = {ts_union(enums["event_type"])};
export type Provenance = {ts_union(enums["provenance"])};

export interface Diagnostic {{
  code: string;
  message: string;
  pointer?: string;
  evidence_refs?: string[];
}}

export interface EvaluatorCoverage {{
  id: string;
  required: boolean;
  status: "evaluated" | "not_applicable" | "skipped" | "disabled" | "error";
  eligible: number;
  evaluated: number;
  skipped: number;
  skip_reasons: Diagnostic[];
}}

export interface EvaluationResultV1 {{
  schema_version: "table.evaluation/1.0";
  evaluation_id: string;
  tool: {{ name: string; version: string }};
  subject: Record<string, unknown>;
  status: EvaluationStatus;
  exit_code: 0 | 1 | 2;
  authority_status: AuthorityStatus;
  coverage: Record<string, unknown>;
  cursor: Record<string, unknown>;
  context: Record<string, string | null>;
  findings: Array<Record<string, unknown>>;
  advisories: Array<Record<string, unknown>>;
  warnings: Diagnostic[];
  errors: Diagnostic[];
}}

export interface TableEventV1 {{
  schema_version: "table.event/1.0";
  event_id: string;
  campaign_id: string;
  session_id: string;
  session_sequence: number;
  source: Record<string, unknown>;
  occurred_at: string;
  recorded_at: string;
  principal: Record<string, unknown>;
  event_type: TableEventType;
  payload: Record<string, unknown>;
  correlation_ids: string[];
  causation_id: string | null;
  audience: string[];
  visibility: "private" | "table" | "public" | "system";
  sensitivity: "normal" | "personal" | "secret";
  provenance: Provenance;
  integrity: Record<string, unknown>;
}}
'''


def evaluation_fixture_text(enums):
    digest = "sha256:" + "0" * 64

    def base(status, authority="self_attested"):
        complete = status in ("checked_clean", "checked_with_advisories", "findings")
        return {
            "schema_version": "table.evaluation/1.0",
            "evaluation_id": f"fixture-{status}-{authority}",
            "tool": {"name": "fixturecheck", "version": "1.0.0"},
            "subject": {"kind": "session", "id": "session-golden",
                        "session_id": "session-golden", "entity_refs": []},
            "status": status,
            "exit_code": 0 if status == "checked_clean" else (1 if complete else 2),
            "authority_status": authority,
            "coverage": {
                "complete": complete, "evidence_required": True,
                "input": 10, "compatible": 10,
                "eligible": 1, "evaluated": 1 if complete else 0,
                "skipped": 0 if complete else 1,
                "evaluators": [{
                    "id": "fixture-rule", "required": True,
                    "status": "evaluated" if complete else "error",
                    "eligible": 1, "evaluated": 1 if complete else 0,
                    "skipped": 0 if complete else 1,
                    "skip_reasons": [] if complete else [{
                        "code": status, "message": f"fixture {status}"
                    }],
                }],
            },
            "cursor": {"checked_through_event_id": "evt-010",
                       "gap_state": "none" if complete else "unknown",
                       "input_digest": digest},
            "context": {"roster_digest": digest, "policy_digest": digest,
                        "config_digest": digest, "source_set_digest": digest,
                        "session_descriptor_digest": digest},
            "findings": [], "advisories": [], "warnings": [], "errors": [],
        }

    finding = {
        "finding_id": "finding-1", "code": "fixture",
        "severity": "finding", "summary": "fixture finding",
        "evidence_refs": ["evt-008"], "effective_policy": {"required": True},
        "policy_version": "fixture/1", "policy_digest": digest,
    }
    advisory = dict(finding, finding_id="advisory-1", severity="advisory",
                    summary="fixture advisory")
    fixtures = []
    for status in enums["status"]:
        item = base(status)
        if status == "checked_with_advisories":
            item["advisories"] = [advisory]
        elif status == "findings":
            item["findings"] = [finding]
        elif item["exit_code"] == 2:
            item["errors"] = [{"code": status, "message": f"fixture {status}"}]
        fixtures.append(item)
    fixtures.append(base("checked_clean", "host_attested"))
    return json.dumps(fixtures, indent=2, sort_keys=True) + "\n"


def normalized_golden_session_text():
    path = CONTRACTS / "golden-session-1.0.jsonl"
    events = [json.loads(line) for line in path.read_text().splitlines()
              if line.strip()]
    for sequence, event in enumerate(events, 1):
        event["session_sequence"] = sequence
    return "".join(json.dumps(event, sort_keys=True, separators=(",", ":")) + "\n"
                   for event in events)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    enums = load_enums()
    outputs = {
        CONTRACTS / "generated_types.py": python_text(enums),
        CONTRACTS / "table-contracts.d.ts": typescript_text(enums),
        CONTRACTS / "evaluation-fixtures-1.0.json": evaluation_fixture_text(enums),
        CONTRACTS / "golden-session-1.0.jsonl": normalized_golden_session_text(),
    }
    stale = [path for path, content in outputs.items()
             if not path.exists() or path.read_text() != content]
    if args.check:
        if stale:
            parser.error("generated contracts are stale: " + ", ".join(map(str, stale)))
        return
    for path, content in outputs.items():
        path.write_text(content)


if __name__ == "__main__":
    main()
